apiVersion: batch/v1
kind: Job
metadata:
  name: enrich-job-listings
spec:
  template:
    spec:
      containers:
      - name: enrich-job-listings
        image: gcr.io/techlistme/enrich-job-listings:latest
        imagePullPolicy: Always
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /app/keys/gbq.json
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        volumeMounts:
        - name: credentials
          mountPath: /app/keys
          readOnly: true
      restartPolicy: OnFailure
      volumes:
      - name: credentials
        secret:
          secretName: gbq
  backoffLimit: 6