---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline-runner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pipeline-runner
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "list", "watch", "delete"]
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-runner
subjects:
- kind: ServiceAccount
  name: pipeline-runner
roleRef:
  kind: Role
  name: pipeline-runner
  apiGroup: rbac.authorization.k8s.io